### ISSUE TITLE
What difference between carlini.py and carlini_robust_precision.py

### ISSUE THREAD

**Issue by nooooonee** [columbia/pixeldp#4]
I wonder what the difference between carlini.py and carlini_robust_precision.py in the code, they look similar.

**Comment by m-lecuyer** [comment]
carlini.py is the regular attack, which succeeds when it changes the class of the target image.

carlini_robust_precision.py considers the attack a success only when the image is robustly miss classified. That is, when the class of the target image is wrong and the prediction is robust to any change of size up to a threshold T. This is used in plots such as Fig. 5 in the paper https://arxiv.org/pdf/1802.03471.pdf

**Comment by pengdan1129** [comment]
I am not sure whether I am wrong.  Because we cannot find the experimental results under C&W attack in the paper, even though authors say the C&W attack is the main attack they used in section evaluation(IV. attack methodology) and Appendix C, and of course, they also implement the C&W attack in the code.  We feel the all reported results in the paper are under the L2 version and L-inf version of PGD attack rather than C&W  attack. I am confused, please point out my faults, if I misunderstand that. Thanks in advance.

**Comment by m-lecuyer** [comment]
All figures in the latest version of the paper use the C&W attack, except Fig. 7, 8 ,9 in the appendix which use our PGD attack (described in Appendix C). The experiments files have a flag to run either attack. The earliest version of the paper has results for the PGD attack.

**Comment by pengdan1129** [comment]
C&W is an unbounded attack, however the horizontal axis of figures 4, 5 is bounded by L_attack. I wonder for the point.

**Comment by m-lecuyer** [comment]
The C&W attack gives the minimum attach found L_min. From that for each L_attack on the x axis, if L_attack < L_min then C&W did not find an attack that small, if L_attack >= L_min it found an attack. So we can still plot those graphs. This is done in the plot scripts https://github.com/columbia/pixeldp/tree/master/plots
